name: Delete Version 🦉


on:
  pull_request:
    types: [ closed ]

jobs:
    rdme-docs:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repo 📚
            uses: actions/checkout@v3

          - name: Generate branch version string
            run: |
              BRANCH_VERSION="${{ github.ref }}"
              echo "BRANCH_VERSION=$BRANCH_VERSION" >> $GITHUB_ENV

          - name: Delete version of docs for branch (if branch is deleted) 🚀
            uses: readmeio/rdme@v8
            with:
                rdme: versions:delete v1.0-${{ env.BRANCH_VERSION }}--key=${{ secrets.README_API_KEY }}
