name: Update ReadMe Docs on Push

on: [push]

jobs:
    rdme-docs:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repo 📚
            uses: actions/checkout@v3

          - name: Generate branch version string
            run: |
              BRANCH_NAME="${{ github.head_ref || github.ref || github.event.ref }}"
              BRANCH_VERSION=$(echo $BRANCH_NAME | tr -cd '0-9.')
              echo "BRANCH_VERSION=$BRANCH_VERSION" >> $GITHUB_ENV

          - name: Delete version of docs for branch (if branch is deleted) 🚀
            uses: readmeio/rdme@v8
            with:
                rdme: docs ${{ env.BRANCH_VERSION }} --version=${{ env.BRANCH_VERSION }} --key=${{ secrets.README_API_KEY }}