name: Update ReadMe Docs on Push

on: [push]

jobs:
    rdme-docs:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repo 📚
            uses: actions/checkout@v3

          - name: Generate branch version string
            run: |
              BRANCH_VERSION="${{ github.ref }}"
              echo "BRANCH_VERSION=$BRANCH_VERSION" >> $GITHUB_ENV

          - name: DryRun for debugging
            uses: readmeio/rdme@v8
            with:
                rdme: docs v1.0 --key=${{ secrets.README_API_KEY }} --version=${{ env.BRANCH_VERSION }} --dryRun

          - name: Update version of docs for branch 🚀
            uses: readmeio/rdme@v8
            with:
                rdme: docs v1.0 --key=${{ secrets.README_API_KEY }} --version=${{ env.BRANCH_VERSION }}